// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQ4FJdQz7UvE-ymY4p58C0wEhEUnZhxA',
    appId: '1:68228281144:web:94ead27801df75a46e87cd',
    messagingSenderId: '68228281144',
    projectId: 'smartgroceryapp-541e0',
    authDomain: 'smartgroceryapp-541e0.firebaseapp.com',
    storageBucket: 'smartgroceryapp-541e0.firebasestorage.app',
    measurementId: 'G-83EML0ELHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpZNFNlZAT0KPSELIobGF8wQp2m6XTz04',
    appId: '1:68228281144:android:fc804963c8b70dbf6e87cd',
    messagingSenderId: '68228281144',
    projectId: 'smartgroceryapp-541e0',
    storageBucket: 'smartgroceryapp-541e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm9sE0vy3H6GmeWAVO-nvnbNCEbLk_jww',
    appId: '1:68228281144:ios:ee30ae312c1dbc3e6e87cd',
    messagingSenderId: '68228281144',
    projectId: 'smartgroceryapp-541e0',
    storageBucket: 'smartgroceryapp-541e0.firebasestorage.app',
    iosBundleId: 'com.example.smartGroceryTracker',
  );
}
